/* 
 * File:   
 * Author: 
 * Comments:
 * Revision history: 
 */
#ifndef EUSART_CFG_H_
#define EUSART_CFG_H_

#include "../../LIB/Std_Types.h"
#include "EUSART_Private.h"



#define EUSART_INTERRUPT_TX_FRETURE_ENABLE      EUSART_ASYNCHRONOUS_INTERRUPT_TX_DISABLE
#define EUSART_INTERRUPT_RX_FRETURE_ENABLE      EUSART_ASYNCHRONOUS_INTERRUPT_RX_DISABLE
#define EUSART_SYNCHRONOUS_ASYNCHONOUS_MODE     EUSART_SYNCHRONOUS_MODE
#define EUSART_ASYNCHRONOUS_SPEED               EUSART_ASYNCHRONOUS_HIGH_SPEED
#define EUSART_nBIT_BAUDRATE_GEN               EUSART_16BIT_BAUDRATE_GEN

#define EUSART_ASYNCHRONOUS_nBit_TX_TRANSMISSION   EUSART_ASYNCHRONOUS_9Bit_TX_DISABLE
#define EUSART_ASYNCHRONOUS_nBit_RC_TRANSMISSION   EUSART_ASYNCHRONOUS_9Bit_RX_DISABLE

#define BAUDRATE_CONFIG_MODE   BAUDRATE_ASYN_8BIT_lOW_SPEED
#define BAUDRATE_CONFIG_VALUE  9600




#endif